### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by Jeiel0rbit** [ninjhacks/unja#5]
I downloaded it via pip. Please note that in this current version, the package is not correct.

`unja -d DOMAIN`

```bash
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/unja", line 5, in <module>
    from unja.__main__ import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/unja/__main__.py", line 8, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by ninjhacks** [comment]
try `pip3 install setuptools`

**Comment by Jeiel0rbit** [comment]
> try `pip3 install setuptools`

It's working. Thanks.
